server:
  port: 8080
spring:
  application:
    name: kraf-tes
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

    consumer:
      group-id: my-group-chat-room
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
  mongodb:
    uri: ${MONGO_CONNECTION_STRING:mongodb://admin:admin123@mongodb:27017/chat_db?authSource=admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Bật Prometheus endpoint

  metrics:
    enable:
      jvm: true          # Bật metric JVM (threads, memory, GC)
      system: true