server:
  port: 8082

spring:
  application:
    name: kraf-tes

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,kafka-0.kafka.dev.svc.cluster.local:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    consumer:
      group-id: kraf-tes-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
    template:
      default-topic: demo-kraft

  mongodb:
    uri: ${MONGO_CONNECTION_STRING:mongodb://admin:admin123@localhost:27017/chat_db?authSource=admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Bật Prometheus endpoint

  metrics:
    enable:
      jvm: true          # Bật metric JVM (threads, memory, GC)
      system: true       # Bật system metric (CPU, file descriptors, memory)
